version: '3'

services:
  db:
    image: postgis/postgis:13-master
    environment:
      - POSTGRES_DB=counterfactualcovid
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    networks:
      - backend
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.docker
    links:
      - db:db
    networks:
      - app
      - backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    networks:
      - app
    ports:
      - "3000:3000"
    stdin_open: true

networks:
  app:
  backend: