version: "3"

services:
  backend:
    build: ./backend
    image: cfcovidcr.azurecr.io/cfcov-backend:latest
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.docker
    expose:
      - "8000"
    restart: always
  frontend:
    build: ./frontend
    image: cfcovidcr.azurecr.io/cfcov-frontend:latest
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always
