version: '3'

services:
  db:
    image: postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    networks:
      - backend
    ports:
      - "9999:5432"
  backend:
    build: ./backend
    command: ["poetry", "run", "python3", "manage.py", "runserver", "0.0.0.0:8000"]
    networks:
      - app
      - backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    networks:
      - app
    ports:
      - "3000:3000"
    stdin_open: true

networks:
  app:
  backend: