version: "3"

services:
  db:
    image: postgis/postgis:13-master
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 0.5G
    environment:
      - POSTGRES_DB=counterfactualcovid
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    networks:
      - backend
    ports:
      - "5432:5432"
    restart: always
  backend:
    build: ./backend
    image: cfvoc.azurecr.io/cfcov-backend:v1
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 2G
        reservations:
          cpus: '2'
          memory: 1.5G
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.docker
    links:
      - db:db
    networks:
      - app
      - backend
    ports:
      - "127.0.0.1:8000:8000"
    restart: always
  frontend:
    build: ./frontend
    image: cfvoc.azurecr.io/cfcov-frontend:v1
    depends_on:
      - backend
    networks:
      - app
    ports:
      - "127.0.0.1:3000:3000"
    restart: always

networks:
  app:
  backend:
