name: enforce-code-style
on: [pull_request]
jobs:
  enforce-style-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install poetry
        run: pip install --upgrade pip poetry setuptools
      - name: Install dependencies
        run: |
          cd backend
          poetry config virtualenvs.create false
          poetry config experimental.new-installer false
          poetry install
      - name: Check style with pylint
        run: pylint backend/*/ --rcfile=.pylintrc
      - name: Run black --check
        run: black --check .
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          black .
          git config --global user.name 'AutoLinter'
          git config --global user.email 'autolinter@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch
          git checkout ${{ github.head_ref }}
          git commit -am "Reformat Python using Black"
          git pull --rebase
          git push
  enforce-style-javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node 15
        uses: actions/setup-node@v2
        with:
          node-version: "15"
      - name: Install prettier
        run: npm install prettier
      - name: Run prettier --check
        run: npx prettier --check .
      - name: If needed, commit prettier changes to the pull request
        if: failure()
        run: |
          npx prettier --write .
          git diff .github/workflows/enforce-code-style.yml
          git config --global user.name 'AutoLinter'
          git config --global user.email 'autolinter@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch
          git checkout ${{ github.head_ref }}
          git commit -am "Reformat Javascript using prettier"
          git pull --rebase
          git push
