name: enforce-code-style
on: [pull_request]
jobs:
  enforce-style-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Black
        run: pip install black
      - name: Run black --check
        run: black --check .
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          black .
          git config --global user.name 'AutoLinter'
          git config --global user.email 'autolinter@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch
          git checkout ${{ github.head_ref }}
          git commit -am "Reformat Python using Black"
          # git push
  enforce-style-javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node 15
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install js-beautify
        run: npm install -g js-beautify
      - name: Run js-beautify
        run: |
          for jsfile in $(find . \( -name '*.js' -o -name '*.jsx' \) -not -path '*/node_modules/*'); do
            js-beautify -r $jsfile;
          done
          if [ "$(git diff)" != "" ]; then
            exit 1
          fi
      - name: If needed, commit js-beautify changes to the pull request
        if: failure()
        run: |
          git config --global user.name 'AutoLinter'
          git config --global user.email 'autolinter@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch
          git checkout ${{ github.head_ref }}
          git commit -am "Reformat Javascript using js-beautify"
          # git push
